services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stonks_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_service
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']

  shared-prisma:
    build:
      context: .
      dockerfile: ./shared/prisma/Dockerfile
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/stonks_db'

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user_service
    depends_on:
      - shared-prisma
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/stonks_db'

  transaction-service:
    build:
      context: .
      dockerfile: ./transaction-service/Dockerfile
    container_name: transaction_service
    depends_on:
      - shared-prisma
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/stonks_db'

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    container_name: order_service
    depends_on:
      - shared-prisma
      - matching-engine-service
    ports:
      - '3002:3002'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/stonks_db'

  matching-engine-service:
    build:
      context: .
      dockerfile: ./matching-engine-service/Dockerfile
    container_name: matching_engine_service
    depends_on:
      - transaction-service
      - redis
    ports:
      - '3003:3003'
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  postgres_data:
  redis_data:
