{
 "title": "Fastify Service Dashboard",
 "tags": [
  "nodejs",
  "fastify"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_summary_seconds{job=\"user-service\", quantile=\"0.5\"}",
     "legendFormat": "{{method}} {{route}} p50"
    },
    {
     "expr": "http_request_summary_seconds{job=\"user-service\", quantile=\"0.9\"}",
     "legendFormat": "{{method}} {{route}} p90"
    },
    {
     "expr": "http_request_summary_seconds{job=\"user-service\", quantile=\"0.99\"}",
     "legendFormat": "{{method}} {{route}} p99"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_summary_seconds_count{job=\"user-service\"}[5m])) by (route, method, status_code)",
     "legendFormat": "{{method}} {{route}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"user-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}